### ISSUE TITLE
Para o service e action, matar o processo quando o tempo for atingido.

### ISSUE THREAD

**Issue by michelalbonico** [IntelAgir-Research-Group/energy-ros2-cpp-python#3]
Como foi feito para o `pub_sub`.

**Comment by binbaragi** [comment]
to tendo esses erros com o fibonaccci 

error: ‘get_default_context’ is not a member of ‘rclcpp’
   28 | tring> args = rclcpp::get_default_context()->get_ros_arguments();

error: ‘get_cmd_line_arguments’ is not a member of ‘rclcpp’
   27 | clcpp::ok() ? rclcpp::get_cmd_line_arguments() : std::vector<std::string>();
